/**
 * Angel-investor economics — pure, unit-tested helpers for the lead-an-SPV
 * flow. A lead commits their own capital and earns carry on the profit of the
 * capital they help raise (the followers' pool), on top of their own return.
 * Mirrors the backend spv_leads model (see backend/api/src/angel).
 */

/** Minimum lead ticket, in the platform's base currency. */
export const ANGEL_MIN_TICKET = 5_000;

/** Default carry a lead takes on followers' profit. */
export const DEFAULT_LEAD_CARRY = 20;

/** Carry is bounded to [0, 30] — matches the DB CHECK on spv_leads.carry_pct. */
export function clampCarry(pct: number): number {
  if (!Number.isFinite(pct)) return DEFAULT_LEAD_CARRY;
  return Math.max(0, Math.min(30, pct));
}

export interface LeadEconomics {
  /** The lead's own committed capital. */
  ownStake: number;
  /** Gross value of the lead's own stake at exit. */
  ownReturn: number;
  /** Profit on the lead's own stake (ownReturn − ownStake). */
  ownProfit: number;
  /** Profit generated by the followers' pool, before carry. */
  followerProfit: number;
  /** Carry the lead earns on the followers' profit. */
  carryEarned: number;
  /** Everything the lead walks away with: own return + carry. */
  totalToLead: number;
}

/**
 * Economics of leading a deal at a given gross exit multiple.
 * @param committed        the lead's own capital
 * @param followersCapital capital the lead's allocation brings alongside them
 * @param carryPct         carry on followers' profit, 0–30
 * @param grossMultiple    exit multiple on invested capital (e.g. 3 = 3×)
 */
export function leadEconomics(
  committed: number,
  followersCapital: number,
  carryPct: number,
  grossMultiple: number,
): LeadEconomics {
  const stake = Math.max(0, committed);
  const followers = Math.max(0, followersCapital);
  const carry = clampCarry(carryPct) / 100;
  const m = Math.max(0, grossMultiple);

  const ownReturn = stake * m;
  const ownProfit = stake * (m - 1);
  const followerProfit = followers * (m - 1);
  // Carry only accrues on positive follower profit.
  const carryEarned = followerProfit > 0 ? followerProfit * carry : 0;
  return {
    ownStake: stake,
    ownReturn,
    ownProfit,
    followerProfit,
    carryEarned,
    totalToLead: ownReturn + carryEarned,
  };
}

/** A retail investor is angel-eligible once their standing is accredited. */
export type Accreditation = 'none' | 'accredited' | 'qualified_purchaser';
export function isAngelEligible(accreditation: Accreditation): boolean {
  return accreditation !== 'none';
}
